name: Rancher redeploy workload
description: An action for redeploying Rancher workload(s)
author: Gokhan Sari
branding:
  icon: package
  color: blue
runs:
  using: docker
  image: docker://th0th/rancher-redeploy-workload:0.81
